#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}" )"
rm -Rf ../functions/notify/vendor
./bundle
cd ../functions/notify
rm -f billing-alerts_notify.zip
zip -r billing-alerts_notify.zip *
aws s3 cp billing-alerts_notify.zip s3://5052/billing-alerts_notify.zip
rm -r billing-alerts_notify.zip
